import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

type Props = Readonly<{
  children: ReactNode;
}>;

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }: Props) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export default layout;
export { metadata };
