name: Setup
runs:
  using: composite
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        cache: yarn
        cache-dependency-path: packages/www/yarn.lock
        node-version-file: packages/www/package.json
    - name: Restore Next.js build cache
      uses: actions/cache@v4
      with:
        path: packages/www/.next/cache
        # Generate a new cache whenever packages or source files change
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
    - name: Install dependencies
      run: yarn install
      shell: bash
      working-directory: packages/www
