on:
  workflow_call:
jobs:
  build:
    name: www
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: packages/www/yarn.lock
          cache: yarn
          node-version: 20.11.1
      - name: Cache
        uses: actions/cache@v4
        with:
          path: packages/www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Dependencies
        run: yarn install
        working-directory: packages/www
      - name: Format
        uses: ./.github/actions/www/format
      - name: Lint
        uses: ./.github/actions/www/lint
      - name: Build
        run: yarn build
        working-directory: packages/www
