name: Deploy
on:
  workflow_dispatch:
    inputs:
      component:
        description: Component
        options:
          - www
        required: true
        type: choice
      version:
        description: Version
        required: true
        type: string
permissions:
  id-token: write
  pages: write
jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download ${{ inputs.component }}-${{ inputs.version }} --dir artifacts --pattern '${{ inputs.component }}-${{ inputs.version }}.zip'
      - name: List Files
        run: ls -R
      - name: Decompress artifact
        run: unzip ${{ inputs.component }}-${{ inputs.version }}.zip.zip
      - name: List Files
        run: ls -R
      # - name: Delete release artifact
      #   run: rm artifact/${{ inputs.component }}-${{ inputs.version }}.zip
      # - name: List Files
      #   run: ls -R
      # - name: Upload workflow artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: artifact
  # deploy:
  #   name: Deploy
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deploy.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: download
  #   steps:
  #     - name: Deploy
  #       id: deploy
  #       uses: actions/deploy-pages@v4
