name: Format
on:
  workflow_call:
jobs:
  www:
    name: www
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/workflows/www/setup
      - name: Check formatting
        run: yarn format:check
        working-directory: packages/www
