name: Pull Request
on:
  pull_request:
jobs:
  format:
    name: Format
    uses: ./.github/workflows/format.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  build:
    name: Build
    needs: [format, lint]
    uses: ./.github/workflows/build.yml
