name: Push main
on:
  push:
    branches: main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-management:
    name: Release Management
    runs-on: ubuntu-latest
    outputs:
      artifact_name: www-${{ steps.release.outputs['packages/www--major'] }}.${{ steps.release.outputs['packages/www--minor'] }}.${{ steps.release.outputs['packages/www--patch'] }}
      release_tag: ${{ steps.release.outputs['packages/www--tag_name'] }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Release management
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-config.json
          manifest-file: release-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
  format:
    name: Format
    needs: release-management
    if: needs.release-management.outputs.releases_created == 'true'
    uses: ./.github/workflows/format.yml
  lint:
    name: Lint
    needs: release-management
    if: needs.release-management.outputs.releases_created == 'true'
    uses: ./.github/workflows/lint.yml
  build:
    name: Build
    needs: [format, lint, release-management]
    if: needs.release-management.outputs.releases_created == 'true'
    uses: ./.github/workflows/build.yml
    with:
      workflow_artifact_name: ${{ needs.release-management.outputs.artifact_name }}
  upload-release-artifact:
    name: Upload Release Artifact
    needs: [build, release-management]
    if: needs.release-management.outputs.releases_created == 'true'
    uses: ./.github/workflows/upload-release-artifact.yml
    with:
      release_tag: ${{ needs.release-management.outputs.release_tag }}
      workflow_artifact_name: ${{ needs.release-management.outputs.artifact_name }}
