name: Upload release artifact
on:
  workflow_call:
    inputs:
      artifact_name:
        description: Workflow artifact to upload
        required: true
        type: string
      release_tag:
        description: Release tag to upload to
        required: true
        type: string
jobs:
  www:
    name: www
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: inputs.artifact_name
          path: inputs.artifact_name
      - name: Compress & package artifact
        run: (cd ${{ inputs.artifact_name }} && zip -r "$OLDPWD/${{ inputs.artifact_name }}.zip" .)
      - name: Upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.release_tag }} ${{ inputs.artifact_name }}.zip
