name: Upload Release Artifact
on:
  workflow_call:
    inputs:
      release_tag:
        description: Release tag to upload to
        required: true
        type: string
      workflow_artifact_name:
        description: Workflow artifact to upload
        required: true
        type: string
jobs:
  www:
    name: www
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.workflow_artifact_name }}
          path: ${{ inputs.workflow_artifact_name }}
      - name: Compress artifact
        run: (cd ${{ inputs.workflow_artifact_name }} && zip -r "$OLDPWD/${{ inputs.workflow_artifact_name }}.zip" .)
      - name: Upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.release_tag }} ${{ inputs.workflow_artifact_name }}.zip
